### ISSUE TITLE
Move sovesove/uxchecklist into this organization

### ISSUE THREAD

**Issue by Neustradamus** [uxchecklist/uxchecklist.github.io#25]
@sovesove: Can you move this original code into uxchecklist organization?

Steps to do:
- Create a temporary org, for example uxchecklist-temp
- Transfer uxchecklist/uxchecklist.github.io into uxchecklist-temp
- Transfer your sovesove/uxchecklist into uxchecklist
- Transfer uxchecklist-temp/uxchecklist.github.io in your personal account
- Remove the uxchecklist-temp temporary org
- Merge the code in the main repository and all branches
- Create a new temporary repo: sovesove/uxchecklist-issues
- Transfer all issues from sovesove/uxchecklist into sovesove/uxchecklist-issues
- Transfer sovesove/uxchecklist-issues into uxchecklist org
- Transfer all issues from uxchecklist/uxchecklist-issues into uxchecklist/uxchecklist
- Rename uxchecklist/uxchecklist to uxchecklist/uxchecklist.github.io
- Delete uxchecklist/uxchecklist-issues
- Archive or delete sovesove/uxchecklist.github.io

It will be perfect now, no lost, redirections will be here :)

**Comment by sovesove** [comment]
Hi @Neustradamus thank you for this. I'm not sure I can understand what problems is this trying to solve, can you add more details? It feels like a laborious process :)

**Comment by Neustradamus** [comment]
@sovesove: "uxchecklist/uxchecklist.github.io
forked from sovesove/uxchecklist"

Example:
- https://github.com/uxchecklist/uxchecklist.github.io/search?q=test

Forks are not really good....

The goal is to have this repo like the main source.

I can do it in few minutes if you give me temporary all rights.
I have already done for several projects without any problems.

**Comment by sovesove** [comment]
Thank you @Neustradamus. To be honest I don't see an issue with it that would justify the work.
Unfortunately I'm not open to share all the rights to it.

Thank you for your input.
